### ISSUE TITLE
Chat icons to use Avatar option

### ISSUE THREAD

**Issue by Cull3411** [Stendarpaval/mob-attack-tool#42] opened 2021-09-23 23:38 UTC
I use Animated Tokens and they don't print to the chat.  I get a broken link icon instead.
I use .webm on some of my Tokens. 

Perhaps look for a .png of the same name in the same directory.  The user would be expected to have an appropriate .png in the right place if they use a .webm token.

Or, I imagine a more difficult option,  provide an Avatar or Token checkbox.

**Comment by Stendarpaval** [comment] 2021-09-25 19:35
This was an interesting bug to look into, thanks for reporting it! 

After reproducing the issue, I noticed that Midi-QOL's apply damage message's token image was displaying properly. So I looked into how they achieved that, and was able to use the same method.

So, as of [v0.3.10](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.3.10) which released just now, .webm token images will display properly in chat messages, as well as the target tab of the Mob Attack dialog. 

I could also add a setting to choose between actor or token image, but I reckon that most DMs prefer to use the token image since shapeshifter actors might have a different actor image. Please let me know if you'd like me to add that setting anyway, or if you run into any other problems with token images. :)

**Comment by Stendarpaval** [comment] 2021-11-10 10:19
I'll go ahead and close this issue. If similar issues pop up, feel free to re-open it.

**Closed by Stendarpaval** 2021-11-10 10:19 UTC
Labels: bug
