### ISSUE TITLE
Damage rolls are all critical when Multiattack module is loaded

### ISSUE THREAD

**Issue by bramdanneels** [Stendarpaval/mob-attack-tool#12] opened 2021-05-02 11:23 UTC
Hey, first of all, great module!
I have ran into an issue where if I activate both this module, and the 5e multiattack module, that all damage rolls of my mob attacks are rolled as critical. This could maybe because the custom dice roller MA5e uses. When disactivating MA5e, the this module works as intended.

**Comment by Stendarpaval** [comment] 2021-05-03 10:41
I've had a look at this and was able to reproduce the behavior after turning off Better Rolls for 5e and Midi-QOL. It seems that it has to do with MA5e overriding dnd5e's `.rollDamage()` method. 

However, the source of the bug was actually my code, since I was still telling dnd5e to hold down the 'alt' key while executing a non-critical damage roll. Holding down the 'alt' key fastforwards the roll (which is what I wanted) but for damage rolls it also signals that it ought to be a crit. 

I've now corrected it to say that it should send the 'hold down shift key' event along with `.rollDamage()`, and from my tests that seems to solve the bug.

I've included this fix in release [v0.1.27](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.1.27). Could you update Mob Attack Tool and let me know if the issue persists? Thank you. :)

**Comment by bramdanneels** [comment] 2021-05-03 16:24
I tested the new version (v0.1.27) and the issue is resolved.
Thanks a lot for the quick solution!

**Comment by Stendarpaval** [comment] 2021-05-03 16:32
Glad to hear it! You're welcome. Since Multiattack 5e was my inspiration for making this module, I enjoy making sure that the two are compatible. ;) 

I'll go ahead and close this issue.

**Closed by Stendarpaval** 2021-05-03 16:32 UTC
Labels: bug
