### ISSUE TITLE
Macros do not work

### ISSUE THREAD

**Issue by Fraxinus1753** [Stendarpaval/mob-attack-tool#37] opened 2021-09-15 06:35 UTC
Thanks for the great module! However, I can't make mob attacks exported as macros work. When I trigger them, nothing happens and I get the attached error message in the console. 

I tried this with D&D 5, Foundry and Mob Attack Tool up to date, and no other module enabled. 

![Mob Attack Tool Error](https://user-images.githubusercontent.com/41876735/133382822-6e7c7e2a-391a-42f2-925a-a186ea722d5f.png)

**Comment by Stendarpaval** [comment] 2021-09-17 16:16
Thanks for reporting this bug! I was able to replicate it. The cause is a new feature introduced in v0.3.7 that allows you to hold down alt or ctrl for rolling with advantage and disadvantage respectively. I kind of neglected to test macros _without_ holding down either of these keys, which is when this error pops up. 

The fix is simple and will be out shortly, right after I check if there've been other bug reports on Foundry's Discord that I might be able to fix in the same release. :)

**Comment by Fraxinus1753** [comment] 2021-09-17 16:30
Alright, thanks for the quick reply and fix!

**Comment by Stendarpaval** [comment] 2021-09-23 18:48
I'll go ahead and close this issue for now. Feel free to reopen it if you run into related bugs in the future :)

**Closed by Stendarpaval** 2021-09-23 18:48 UTC
Labels: bug

**Comment by Fraxinus1753** [comment] 2021-09-24 07:44
I tried with the new version and it works perfectly, thanks for the quick fix!
