### ISSUE TITLE
Deselecting all tokens while Mob Attack Tool is open causes error

### ISSUE THREAD

**Issue by benbarbour** [Stendarpaval/mob-attack-tool#28] opened 2021-06-30 18:24 UTC
**Steps to Reproduce**

1. Select one or more tokens
2. Open Mob Attack Tool - you will see selected tokens in the tool window
3. Deselect all tokens

```
TypeError: An error occurred while rendering MobAttackDialog 95: canvas.tokens.controlled[0] is undefined
    getData mobAttackTool.js:141
    _render foundry.js:2042
    call_wrapped libWrapper-wrapper.js:465
    <anonymous> listeners.js:75
    0 libWrapper-wrapper.js:160
    _render foundry.js:2729
    render foundry.js:2004
    <anonymous> mobAttack.js:42
    _call lib-wrapper.js line 1 > eval:4
    callAll foundry.js:153
    release foundry.js:18906
    releaseAll foundry.js:19599
    _onClickLeft foundry.js:19914
    _onClickLeft foundry.js:17956
    call_wrapped libWrapper-wrapper.js:465
    canvasOnClickLeft smartTarget.js:99
    call_wrapper libWrapper-wrapper.js:574
    0 libWrapper-wrapper.js:162
    callback foundry.js:35554
    _handleClickLeft foundry.js:35741
    _handleMouseDown foundry.js:35721
    call_wrapped libWrapper-wrapper.js:465
    _handleMouseDown_Wrapper zoom-pan-options.js:164
    <anonymous> zoom-pan-options.js:304
    call_wrapper libWrapper-wrapper.js:574
    0 libWrapper-wrapper.js:162
    emit index.js:181
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8
foundry.js:2006:14
```

Re-selecting tokens no longer updates the window. It must be closed and opened again to resume use.

**Comment by Stendarpaval** [comment] 2021-06-30 20:13
Thanks for making this issue! I was able to reproduce the bug, good catch! This bug only occurs if you don't have any saved mobs. (I didn't encounter it myself because I almost always had a saved mob during testing...)

I'll quickly add a few checks that should prevent this from happening and afterward push out a patch. Probably won't take too long. :)

**Comment by Stendarpaval** [comment] 2021-06-30 22:15
This bug should be fixed in version [0.2.20](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.20) that I released just now. Could you update to the new version and let me know if it fixed it for you too? That would be great :)

**Comment by benbarbour** [comment] 2021-06-30 23:32
LGTM!

**Comment by Stendarpaval** [comment] 2021-07-01 10:35
Thanks for checking! In that case I will go ahead and close this issue. Feel free to reopen it if you run into related bugs in the future.

**Closed by Stendarpaval** 2021-07-01 10:35 UTC
Labels: bug
