### ISSUE TITLE
Mob attacks don't actually roll.

### ISSUE THREAD

**Issue by mike-marshall0164** [Stendarpaval/mob-attack-tool#7] opened 2021-03-22 16:16 UTC
I took a glance at this module and noticed that the mobs don't actually roll their attacks. Is this intentional? I don't really understand the purpose of having a static function to determine a fixed amount of attackers hits. Could we get an option to actually roll for each mob for determining hits? I can possibly help but I'd like to know if I'm missing some rule or something that I just don't understand.

**Comment by Stendarpaval** [comment] 2021-03-22 18:42
That's right, there aren't any attack rolls and that is intentional. This tool implements the mechanics as described in "Handling Mobs" on page 250 of the Dungeon Master's Guide. 

However, others have also asked about including an option to actually roll for each creature of a mob. So I'll work on that next.

**Comment by Stendarpaval** [comment] 2021-03-22 23:15
As you can read in [release notes of v0.1.11](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.1.11), I've added the option to let mob attacks be rolled individually. And to have the rolls be properly limited to those attackers that actually have the selected weapon. 

If you happen to have some time to try it out, please let me know if you experience any bugs. 🙃

**Comment by mike-marshall0164** [comment] 2021-03-23 00:35
Wow, thanks so much for this. This is really awesome! I'm not using better rolls, but midi-qol + dice so nice. I don't see the individual attack rolls since you have that check in the better rolls [https://github.com/Stendarpaval/mob-attack-tool/blob/dad0ceb482cdd8c90a1ccb1a7fca7484a4691019/scripts/mobAttackTool.js#L284-L288](block) 

I think there might be a bug with the midi damage roll on L307 with the actor. For me it's showing the target being the one doing the damage to himself instead of one of the selected mobs.

**Comment by Stendarpaval** [comment] 2021-03-23 07:02
Showing individual attack rolls without using Better Rolls is going to be a bit more challenging, since I'm not completely sure if Midi-QOL allows me to manually set attack roll results. I'll have to experiment for a bit.

As for that bug, are you sure that you didn't have the targeted actor selected as well? If that actor had the same weapon option as the mob, then it might have been used in the mob attack. If the targeted actor wasn't selected, could you share a screenshot in order for me to reproduce the bug?

Thanks for telling me about that bug, by the way!

**Comment by mike-marshall0164** [comment] 2021-03-23 16:55
![Screenshot 2021-03-23 090403](https://user-images.githubusercontent.com/8354913/112178279-de9be700-8bb6-11eb-8953-a151c0dde967.png)

I remember reading something about midi qol that there's a limitation on how he does attack rolls piped into the damage only. Hence the weird rolls 9999. I'm sure he's working on a refactor of the workflows to allow for attack rolls and passing them into the damage workflow. 

I'd have to pull it down and figure out how to run a custom module to help debug further. My hunch is that it's something getting passed to the dmageOnlyWorkflow.

**Comment by mike-marshall0164** [comment] 2021-03-24 00:41
I pulled down the repo and am playing with it locally. I think it needs to be more like this for midi. 

`let dmgWorkflow = new MidiQOL.DamageOnlyWorkflow(data.weapons[key].options.actor, data.targetToken, damageRoll.total, damageTypeLabels[0], [data.targetToken], damageRoll, {"flavor": `${key} - Damage Roll (${damageType})`, itemData: data.weapons[key], itemCardId:  "new" });`

**Comment by Stendarpaval** [comment] 2021-03-27 19:55
Since your pull request #9 was merged and I've added the improvements that I mentioned in that request as part of release [v0.1.12](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.1.12), I think it's fair to close this issue now. 

Thanks for helping me improve Mob Attack Tool! If there are any other issues / possible improvements / bugs, feel free to make a new issue.

**Closed by Stendarpaval** 2021-03-27 19:55 UTC
Labels: enhancement, question
