### ISSUE TITLE
Clicking "Show Options" in the Attacks tab does nothing

### ISSUE THREAD

**Issue by benbarbour** [Stendarpaval/mob-attack-tool#27] opened 2021-06-30 18:21 UTC
Except print this console error:

```
Uncaught (in promise) TypeError: html.find(...)[0] is undefined
    activateListeners https://my.foundry.com/modules/mob-attack-tool/scripts/mobAttackTool.js:852
```

**Comment by Stendarpaval** [comment] 2021-06-30 20:10
Thanks for reporting the issue. I can't replicate this behavior, but the line it originates from gave me a clue what's going on. 

(That bit of is designed to "remember" what the dropdown menu for rollType was at when showing or hiding these options, but apparently that doesn't really work when it can't search through the changed html.)

Long story short, I'll comment these lines out for now and release a patch shortly. Before I do that, I'll check the other issue to see if I can fix that in the same patch.

**Comment by Stendarpaval** [comment] 2021-06-30 22:12
Since [v0.2.20](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.20) is out and has commented out the offending lines, could you please update to the new version and tell me if you run into any bugs? That'd be of great help, since I wasn't able to reproduce this bug.

**Comment by benbarbour** [comment] 2021-06-30 23:32
LGTM!

**Comment by Stendarpaval** [comment] 2021-07-01 10:36
Nice! In that case I'll go ahead and close this issue. If related bugs pop up, don't hesitate to reopen it again. :)

**Closed by Stendarpaval** 2021-07-01 10:36 UTC
Labels: bug
