### ISSUE TITLE
Feature request: Handle Pack tactics advantage

### ISSUE THREAD

**Issue by caewok** [Stendarpaval/mob-attack-tool#5] opened 2021-03-06 21:43 UTC
Great module; thanks! Love the interface. One request: Add a check box so the DM can choose to attack with advantage, for creatures like kobolds who have pack tactics. I know, the DMG does not address using pack tactics, so I would be fine with whatever you decide works. There are discussions about this online. 

Mathematically, advantage roughly gives a +5 to attack. So a simple way to do this would be to just add a +5 to the creatures' attack bonus, and then calculate the number of hits. One could try to be more precise by running some simulations to see how advantage would interact with multiple attacks. If you are interested, I could probably set up a basic monte carlo sim.

**Comment by Stendarpaval** [comment] 2021-03-07 00:38
That sounds interesting! 

My priority for this Tool is to help people speed up lengthy encounters with lots of similar enemies, and to achieve that Mob Attacks by design sacrifice precision (in terms of combat options like multiattack) for speed. In other words, I'm going to focus on making it faster and easier to use first. 

Having said that, the ability to handle advantage/disadvantage is definitely something I'd be willing to include as an option you can change in settings. 

The initial implementation might be adding the ability to write a Roll formula that is added to / subtracted from the d20 needed. Following that, I might add support for custom Mob Attack tables, which would probably mesh well with your simulation plans.

**Comment by caewok** [comment] 2021-03-07 02:02
Maybe include an option in settings that lets the GM set the default bonus for advantage or disadvantage. Probably a roll formula if possible, otherwise a flat bonus.  Then add a check box in the pop up that lets the GM include that bonus, and optionally change it for one-offs. (Fill in the bonus value with the default but let the GM change it on the fly.)

I agree that custom mob attack tables would be useful. There are definitely a few floating around the internets. A simple JSON import/export from settings would probably do the trick.
    On Saturday, March 6, 2021, 04:39:07 PM PST, Stendarpaval <notifications@github.com> wrote:  
 
 


That sounds interesting!

My priority for this Tool is to help people speed up lengthy encounters with lots of similar enemies, and to achieve that Mob Attacks by design sacrifice precision (in terms of combat options like multiattack) for speed. In other words, I'm going to focus on making it faster and easier to use first.

Having said that, the ability to handle advantage/disadvantage is definitely something I'd be willing to include as an option you can change in settings.

The initial implementation might be adding the ability to write a Roll formula that is added to / subtracted from the d20 needed. Following that, I might add support for custom Mob Attack tables, which would probably mesh well with your simulation plans.

**Comment by Stendarpaval** [comment] 2021-03-08 11:00
I've added some settings in v0.1.5 that allow users to show/hide a drop-down list in the tool dialog to choose advantage/normal/disadvantage. In settings you can also set a flat value which is used as the advantage bonus and disadvantage penalty. 

I might change this to an input field on the tool dialog like you suggested, or perhaps a slider for ease of use. I'll look into that later.

**Comment by Stendarpaval** [comment] 2021-06-04 22:56
It has taken quite some time, but I have added an initial implementation of custom mob tables in v0.2.5 (and v0.2.6). I'll be adding a way to add or remove rows later. Let me know if you run into any bugs!

**Comment by Stendarpaval** [comment] 2021-06-05 21:07
Alright, with [v0.2.10](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.10) you can now customize the mob table quite extensively. Therefore I will close this issue. Feel free to reopen it if you encounter any bugs!

**Closed by Stendarpaval** 2021-06-05 21:07 UTC
Labels: enhancement

**Comment by caewok** [comment] 2021-06-06 04:27
Thanks so much!
