### ISSUE TITLE
Bonus AC not being calculated getting this error

### ISSUE THREAD

**Issue by Avitale34** [Stendarpaval/mob-attack-tool#36] opened 2021-09-05 01:40 UTC
The bonus AC section under Targets is not working properly, throwing this error when trying to apply a bonus.

mobAttackTool.js:670 Uncaught (in promise) TypeError: acMod.isNaN is not a function
[Detected 1 package: mob-attack-tool]
    at HTMLButtonElement.<anonymous> (mobAttackTool.js:670)
    at HTMLFormElement.dispatch (jquery.min.js:2)
    at HTMLFormElement.v.handle (jquery.min.js:2)
(anonymous) @ mobAttackTool.js:670
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by Stendarpaval** [comment] 2021-09-05 11:56
Thank you for reporting this error! The cause of that error is a mistake that I ran into several releases ago, but apparently I only fixed it for other parts of Mob Attack Tool. 

As of [v0.3.7](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.3.7), however, you should no longer run into that problem when using the AC modifier.

**Comment by Avitale34** [comment] 2021-09-05 12:46
Works great!!

**Comment by Stendarpaval** [comment] 2021-09-06 07:51
Good to hear! I'll go ahead and close this issue for now, but don't hesitate to reopen it if you run into similar errors again in the future. :)

**Closed by Stendarpaval** 2021-09-06 07:51 UTC
Labels: bug
